package provider

import (
	"context"
	"fmt"
	"strings"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &workloadIdentityBindingResource{}
	_ resource.ResourceWithConfigure   = &workloadIdentityBindingResource{}
	_ resource.ResourceWithImportState = &workloadIdentityBindingResource{}
)

type (
	workloadIdentityBindingResource struct {
		client *dtrack.Client
		semver *Semver
	}

	workloadIdentityBindingResourceModel struct {
		ID             types.String `tfsdk:"id"`
		UUID           types.String `tfsdk:"uuid"`
		ServiceAccount types.String `tfsdk:"service_account"`
		ProviderName   types.String `tfsdk:"provider_name"`
		Subject        types.String `tfsdk:"subject"`
		Condition      types.String `tfsdk:"condition"`
		CreatedAt      types.Int64  `tfsdk:"created_at"`
	}
)

func NewWorkloadIdentityBindingResource() resource.Resource {
	return &workloadIdentityBindingResource{}
}

func (*workloadIdentityBindingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workload_identity_binding"
}

func (*workloadIdentityBindingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Workload Identity Binding, which allows tokens from a Workload Identity Provider matching a subject " +
			"to authenticate as a Service Account. Bindings cannot be modified, so any change replaces the binding. Requires API >= 5.2.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Identifier for the Workload Identity Binding, in the format <ServiceAccountName>/<UUID>.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"uuid": schema.StringAttribute{
				Description: "UUID for the Workload Identity Binding as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"service_account": schema.StringAttribute{
				Description: "Name of the Service Account which the binding authenticates as, without the `svc:` prefix.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"provider_name": schema.StringAttribute{
				Description: "Name of the Workload Identity Provider whose tokens are trusted.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"subject": schema.StringAttribute{
				Description: "The `sub` claim to match, such as `repo:acme/app:ref:refs/heads/main`. A trailing `*` makes it a prefix match, " +
					"whose prefix must end with `:` or `/`, such as `repo:acme/app:*`. For SPIFFE providers, the prefix must end with `/`.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"condition": schema.StringAttribute{
				Description: "Optional CEL expression over the token's claims which must evaluate to true, with the claims available as the `claims` map, " +
					"such as `claims.ref == \"refs/heads/main\"`.",
				Optional: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_at": schema.Int64Attribute{
				Description: "Timestamp of when the Workload Identity Binding was created, in milliseconds since the Unix epoch.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *workloadIdentityBindingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan workloadIdentityBindingResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceAccount := plan.ServiceAccount.ValueString()
	bindingReq := dtrack.CreateWorkloadIdentityBindingRequest{
		ProviderName: plan.ProviderName.ValueString(),
		Subject:      plan.Subject.ValueString(),
		Condition:    plan.Condition.ValueString(),
	}

	tflog.Debug(ctx, "Creating Workload Identity Binding", map[string]any{
		"service_account": serviceAccount,
		"provider_name":   bindingReq.ProviderName,
		"subject":         bindingReq.Subject,
	})

	bindingRes, err := r.client.ServiceAccount.CreateWorkloadIdentityBinding(ctx, serviceAccount, bindingReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Workload Identity Binding",
			"Error in: "+serviceAccount+", in original error: "+err.Error(),
		)
		return
	}

	binding, err := r.findBinding(ctx, serviceAccount, bindingRes.UUID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error while creating Workload Identity Binding",
			"Error reading after creation in: "+serviceAccount+"/"+bindingRes.UUID.String()+", in original error: "+err.Error(),
		)
		return
	}
	newState := newWorkloadIdentityBindingModel(serviceAccount, *binding, plan.Condition)

	diags = resp.State.Set(ctx, newState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created Workload Identity Binding", map[string]any{
		"id":              newState.ID.ValueString(),
		"service_account": newState.ServiceAccount.ValueString(),
	})
}

func (r *workloadIdentityBindingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state.
	var state workloadIdentityBindingResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh.
	id, diag := TryParseUUID(state.UUID, LifecycleRead, path.Root("uuid"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	serviceAccount := state.ServiceAccount.ValueString()
	tflog.Debug(ctx, "Reading Workload Identity Binding", map[string]any{
		"id":              state.ID.ValueString(),
		"service_account": serviceAccount,
	})

	binding, err := r.findBinding(ctx, serviceAccount, id)
	if err != nil {
		err := err.Error()
		missing := err == "did not find item" ||
			err == "{\"type\":\"about:blank\",\"title\":\"Not Found\",\"detail\":\"The requested resource could not be found.\",\"status\":404} (status: 404)"
		if missing {
			tflog.Warn(ctx, "Unable to read missing Workload Identity Binding. Will be removed from state.", map[string]any{
				"id":              state.ID.ValueString(),
				"service_account": serviceAccount,
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error when reading Workload Identity Binding.",
			"Error in binding with id: "+state.ID.ValueString()+", in original error: "+err,
		)
		return
	}

	newState := newWorkloadIdentityBindingModel(serviceAccount, *binding, state.Condition)

	// Update state.
	diags = resp.State.Set(ctx, newState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Workload Identity Binding", map[string]any{
		"id":              newState.ID.ValueString(),
		"service_account": newState.ServiceAccount.ValueString(),
	})
}

func (*workloadIdentityBindingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Nothing to Update. This resource only has Create, Delete actions.
	// Verifies that stored state is conformant to model.
	var plan workloadIdentityBindingResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *workloadIdentityBindingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state.
	var state workloadIdentityBindingResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(state.UUID, LifecycleDelete, path.Root("uuid"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	serviceAccount := state.ServiceAccount.ValueString()

	// Execute.
	tflog.Debug(ctx, "Deleting Workload Identity Binding", map[string]any{
		"id":              state.ID.ValueString(),
		"service_account": serviceAccount,
	})
	err := r.client.ServiceAccount.DeleteWorkloadIdentityBinding(ctx, serviceAccount, id)
	if err != nil {
		err := err.Error()
		if err == "{\"type\":\"about:blank\",\"title\":\"Not Found\",\"detail\":\"The requested resource could not be found.\",\"status\":404} (status: 404)" {
			tflog.Warn(ctx, "Unable to delete missing Workload Identity Binding. Ignoring since is desired state.", map[string]any{
				"id":              state.ID.ValueString(),
				"service_account": serviceAccount,
			})
			return
		}
		resp.Diagnostics.AddError(
			"Unable to delete Workload Identity Binding",
			"Unexpected error when trying to delete Workload Identity Binding: "+state.ID.ValueString()+", from error: "+err,
		)
		return
	}
	tflog.Debug(ctx, "Deleted Workload Identity Binding", map[string]any{
		"id":              state.ID.ValueString(),
		"service_account": serviceAccount,
	})
}

func (r *workloadIdentityBindingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, "/")
	if len(idParts) != 2 || idParts[0] == "" || idParts[1] == "" {
		resp.Diagnostics.AddError(
			"Unexpected import id",
			"Expected id in format <ServiceAccountName>/<UUID>. Received "+req.ID,
		)
		return
	}
	serviceAccount := idParts[0]
	id, diag := TryParseUUID(types.StringValue(idParts[1]), LifecycleImport, path.Root("uuid"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	tflog.Debug(ctx, "Importing Workload Identity Binding", map[string]any{
		"id":              req.ID,
		"service_account": serviceAccount,
	})
	binding, err := r.findBinding(ctx, serviceAccount, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Within Import, unable to identify Workload Identity Binding.",
			"Unexpected error: "+err.Error(),
		)
		return
	}

	bindingState := newWorkloadIdentityBindingModel(serviceAccount, *binding, types.StringNull())

	diags := resp.State.Set(ctx, bindingState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Workload Identity Binding", map[string]any{
		"id":              bindingState.ID.ValueString(),
		"service_account": bindingState.ServiceAccount.ValueString(),
	})
}

func (r *workloadIdentityBindingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}

// Bindings can only be listed per Service Account, so the binding is located by UUID within that list.
func (r *workloadIdentityBindingResource) findBinding(ctx context.Context, serviceAccount string, id uuid.UUID) (*dtrack.WorkloadIdentityBinding, error) {
	return FindPagedV5(
		func(pageToken string, limit uint32) (dtrack.PageV5[dtrack.WorkloadIdentityBinding], error) {
			return r.client.ServiceAccount.ListWorkloadIdentityBindings(ctx, serviceAccount, pageToken, limit)
		},
		func(binding dtrack.WorkloadIdentityBinding) bool {
			return binding.UUID == id
		},
	)
}

// Maps the API response to the Terraform model. An absent condition is null, unless it was previously known as empty.
func newWorkloadIdentityBindingModel(
	serviceAccount string,
	binding dtrack.WorkloadIdentityBinding,
	condition types.String,
) workloadIdentityBindingResourceModel {
	model := workloadIdentityBindingResourceModel{
		ID:             types.StringValue(fmt.Sprintf("%s/%s", serviceAccount, binding.UUID.String())),
		UUID:           types.StringValue(binding.UUID.String()),
		ServiceAccount: types.StringValue(serviceAccount),
		ProviderName:   types.StringValue(binding.ProviderName),
		Subject:        types.StringValue(binding.Subject),
		Condition:      types.StringNull(), // Conditionally Set Below.
		CreatedAt:      types.Int64Value(binding.CreatedAt),
	}
	if !condition.IsNull() || binding.Condition != "" {
		model.Condition = types.StringValue(binding.Condition)
	}
	return model
}
